export const PredefinedTypeNames = Object.freeze(
    {
        module: "module",
        type: "type",
        any: "any",
        unknown: "unknown",
        never: "never",
        unit: "unit",
        str: "str",
        bool: "bool",
        i8: "i8",
        i16: "i16",
        i32: "i32",
        i64: "i64",
        isz: "isz",
        u8: "u8",
        u16: "u16",
        u32: "u32",
        u64: "u64",
        usz: "usz",
        f16: "f16",
        f32: "f32",
        f64: "f64",
    });