export enum SyntaxKind {
    InvalidSyntax,

    // SyntaxTokens

    EofToken,
    IdentifierToken,

    I8LiteralToken,
    U8LiteralToken,
    I16LiteralToken,
    U16LiteralToken,
    I32LiteralToken,
    U32LiteralToken,
    I64LiteralToken,
    U64LiteralToken,
    F16LiteralToken,
    F32LiteralToken,
    F64LiteralToken,
    StrLiteralToken,

    AmpersandToken,
    AmpersandAmpersandToken,
    AmpersandEqualsToken,
    ExclamationToken,
    ExclamationEqualsToken,
    BraceOpenToken,
    BraceCloseToken,
    BracketOpenToken,
    BracketCloseToken,
    BracketOpenBracketCloseToken,
    ColonToken,
    CommaToken,
    DotToken,
    DotDotToken,
    EqualsToken,
    EqualsEqualsToken,
    GreaterThanToken,
    GreaterThanEqualsToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanEqualsToken,
    CaretToken,
    CaretEqualsToken,
    HookToken,
    HookHookToken,
    HookHookEqualsToken,
    LessThanToken,
    LessThanEqualsToken,
    LessThanLessThanToken,
    LessThanLessThanEqualsToken,
    MinusToken,
    MinusEqualsToken,
    ParenthesisOpenToken,
    ParenthesisCloseToken,
    ParenthesisOpenParenthesisCloseToken,
    PercentToken,
    PercentEqualsToken,
    BarToken,
    PipeEqualsToken,
    BarBarToken,
    PlusToken,
    PlusEqualsToken,
    SemicolonToken,
    SlashToken,
    SlashEqualsToken,
    AsteriskToken,
    StarEqualsToken,
    AsteriskAsteriskToken,
    StarStarEqualsToken,
    TildeToken,

    EqualsGreaterThanToken,
    MinusGreaterThanToken,

    AsKeyword,
    IfKeyword,
    ImplicitKeyword,
    ElseKeyword,
    ExplicitKeyword,
    WhileKeyword,
    ForKeyword,
    ContinueKeyword,
    BreakKeyword,
    ReturnKeyword,

    AnyKeyword,
    ErrKeyword,
    UnknownKeyword,
    NeverKeyword,
    UnitKeyword,
    TypeKeyword,
    StrKeyword,
    BoolKeyword,
    I8Keyword,
    I16Keyword,
    I32Keyword,
    I64Keyword,
    IszKeyword,
    U8Keyword,
    U16Keyword,
    U32Keyword,
    U64Keyword,
    UszKeyword,
    F16Keyword,
    F32Keyword,
    F64Keyword,

    ModuleKeyword,
    StructKeyword,

    TrueKeyword,
    FalseKeyword,
    NullKeyword,

    ThisKeyword,

    LineBreakTrivia,
    WhiteSpaceTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia,
    InvalidTextTrivia,

    // Types
    AnyType,
    ErrType,
    UnknownType,
    NeverType,
    UnitType,
    TypeType,
    StrType,
    BoolType,
    I8Type,
    I16Type,
    I32Type,
    I64Type,
    IszType,
    U8Type,
    U16Type,
    U32Type,
    U64Type,
    UszType,
    F16Type,
    F32Type,
    F64Type,
    ArrayType,
    ErrorType,
    LambdaType,
    NamedType,
    MaybeType,
    PointerType,
    UnionType,

    // Other

    Parameter,
    Argument,

    CompilationUnit,

    SimpleName,
    QualifiedName,

    GlobalDeclaration,
    LocalDeclaration,

    ExpressionStatement,

    // Expressions

    I8LiteralExpression,
    U8LiteralExpression,
    I16LiteralExpression,
    U16LiteralExpression,
    I32LiteralExpression,
    U32LiteralExpression,
    I64LiteralExpression,
    U64LiteralExpression,
    F16LiteralExpression,
    F32LiteralExpression,
    F64LiteralExpression,
    StrLiteralExpression,
    TrueLiteralExpression,
    FalseLiteralExpression,
    NullLiteralExpression,

    ModuleExpression,
    StructExpression,

    NameExpression,

    BlockExpression,

    ArrayInitializerExpression,
    StructInitializerExpression,
    PropertyInitializerExpression,

    ElementAccessExpression,
    CallExpression,
    MemberAccessExpression,
    ConversionExpression,

    GroupExpression,
    LambdaExpression,

    UnaryPlusExpression,
    UnaryMinusExpression,
    OnesComplementExpression,
    NotExpression,

    AddExpression,
    SubtractExpression,
    MultiplyExpression,
    DivideExpression,
    ModuloExpression,
    PowerExpression,
    LeftShiftExpression,
    RightShiftExpression,
    LogicalOrExpression,
    LogicalAndExpression,
    BitwiseOrExpression,
    BitwiseAndExpression,
    ExclusiveOrExpression,
    EqualsExpression,
    NotEqualsExpression,
    LessThanExpression,
    LessThanOrEqualExpression,
    GreaterThanExpression,
    GreaterThanOrEqualExpression,
    CoalesceExpression,

    AssignmentExpression,

    InitValueExpression,

    IfExpression,
    ElseClauseExpression,
    WhileExpression,

    ContinueExpression,
    BreakExpression,
    ReturnExpression,
}
